import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import SupabaseProvider from "@/lib/supabase/SupabaseProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        data-qb-installed="true"
        cz-shortcut-listen="true"
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ClerkProvider>
          <SupabaseProvider>
            <Navbar />
            <main className=" flex-1 bg-gradient-to-br from-blue-50 via-white to-purple-50 ">
              {children}
            </main>
          </SupabaseProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
